# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Bones"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Bare bones extensible project structure"
homepage = "https://github.com/Im5tu/hugo-bones"
tags = ["blog"]
features = ["html5", "css3"]
min_version = 0.17

[author]
  name = "Stuart Blackler"
  homepage = "https://im5tu.io/"